apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bvsatyanarayana/example_k8s.git
    targetRevision: HEAD
    path: argo/example-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: example-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      alloweEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
    retry:
      limit: 0
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 1d